# 存储位置 Where they are

collections:
  technical-writing:
    output: true


# 输出 Outputing

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "content-share"
      permalink: "/:categories/:title:output_ext"
  - scope:
      path: "*/index.html"
    values:
      layout: "page-container"
  - scope:
      path: ""
    values:
      layout: "default"
      author: "王烨"

disable_disk_cache: BOOL


# 插件 Plugins
whitelist:
  - jekyll-toc
plugins:
  - jekyll-toc


