# 存储位置 Where they are
collections:
  markdown-tutorial:
    output: true
    docType: tutorial
    subject: Markdown
    permalink: doc-tech/:collection/:name:output_ext
    coverIamge: "/assets/images/tutorial/markdown-header-image-5mpx.jpg"
    sections:
      - en: "Basic syntax"
        cn: "基本语法"
      - en: "Extended syntax"
        cn: "扩展语法"
      - en: "kramdown syntax"
        cn: "kramdown 语法"


# 输出 Outputing

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      isPost: true
      layout: "content-share"
      permalink: "/:categories/:title:output_ext"
  - scope:
      path: ""
      type: "markdown-tutorial"
    values:
      layout: "tutorial"
      headerImage: "/assets/images/tutorial/markdown-header-image-20mpx.jpg"
  - scope:
      path: "*/index.html"
    values:
      layout: "page-container"
  - scope:
      path: ""
    values:
      layout: "default"
      author: "王烨"

disable_disk_cache: BOOL


