# 存储位置 Where they are
collections:
  markdown-tutorial:
    output: true
    classification: tutorial
    tutorialName: "Markdown 教程"
    permalink: /:collection/:name:output_ext
    order:
      - index.md
      - title.md
      - paragraph.md


# 输出 Outputing

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      isPost: true
      layout: "content-share"
      permalink: "/:categories/:title:output_ext"
  - scope:
      path: ""
      type: "markdown-tutorial"
    values:
      layout: "tutorial"
  - scope:
      path: "*/index.html"
    values:
      layout: "page-container"
  - scope:
      path: ""
    values:
      layout: "default"
      author: "王烨"

disable_disk_cache: BOOL


# 插件 Plugins
whitelist:
  - jekyll-toc
plugins:
  - jekyll-toc


