# 存储位置 Where they are
collections:
  markdown-tutorial:
    output: true
    docType: tutorial
    subject: Markdown
    permalink: doc-tech/:collection/:name:output_ext
    coverIamge: "/assets/images/tutorial/markdown-header-image-5mpx.jpg"
    icon: "/assets/images/icons/markdown-icon-purple-white.svg"
    sections:
      - en: "Basic syntax"
        cn: "基本语法"
      - en: "Extended syntax"
        cn: "扩展语法"
      - en: "kramdown syntax"
        cn: "kramdown 语法"
      - en: "Pandoc syntax"
        cn: "Pandoc 语法"
  electric-machinery-principles:
    output: true
    docType: tutorial
    subject: 电机中的物理学
    permalink: ics-tutorial/:collection/:name:output_ext
    coverIamge: "/assets/images/tutorial/ics-tutorials/electric-machine-header-image.svg"
    icon: "/assets/images/icons/markdown-icon-purple-white.svg"
    sections:
      - en: "Basic syntax"
        cn: "基本语法"
      - en: "Extended syntax"
        cn: "扩展语法"
      - en: "kramdown syntax"
        cn: "kramdown 语法"
      - en: "Pandoc syntax"
        cn: "Pandoc 语法"
  manual-writing-cases:
    output: true
    docType: manual
    subject: 技术写作
    permalink: style-guides/:collection/:name:output_ext
    coverImage:
    icon: "/assets/images/icons/techWriting.svg"
    sections:
      - en: "Equipments"
        cn: "机械设备"
      - en: "Instruments"
        cn: "仪器仪表"


# 输出 Outputing

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      isPost: true
      layout: "post"
      permalink: "/:categories/:title:output_ext"
  - scope:
      path: ""
      type: "markdown-tutorial"
    values:
      layout: "tutorial"
      headerImage: "/assets/images/tutorial/markdown-header-image-20mpx.jpg"
  - scope:
      path: ""
      type: "manual-writing-cases"
    values:
      layout: "tutorial"
      headerImage: "/assets/images/tutorial/markdown-header-image-20mpx.jpg"
  - scope:
      path: "*/index.html"
    values:
      layout: "page-container"
  - scope:
      path: ""
    values:
      layout: "default"
      author: "王烨"

disable_disk_cache: BOOL

