# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 技术传播百态说
description:  解密文档技术，精研技术写作，评说行业百态
url: "https://www.docsimpo.work"

# 存储位置 Where they are
collections:
  markdown-tutorial:
    output: true
    docType: tutorial
    permalink: doc-tech/:collection/:name:output_ext
  electric-machinery-principles:
    output: true
    docType: tutorial
    permalink: ics-tutorials/:collection/:name:output_ext
  style-guide-en:
    output: true
    docType: tutorial
    permalink: style-guides/:collection/:name:output_ext


# 输出 Outputing

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      author: "王烨"
  - scope:
      path: ""
      type: "posts"
    values:
      isPost: true
      layout: "post"
      permalink: "/:categories/:title:output_ext"
  - scope:
      path: ""
      type: "markdown-tutorial"
    values:
      layout: "tutorial-2l"
      headerImage: "/assets/images/tutorial/markdown-header-image-20mpx.jpg"
  - scope:
      path: ""
      type: "style-guide-en"
    values:
      layout: "tutorial-2l"
      headerImage: "/assets/images/tutorial/markdown-header-image-20mpx.jpg"
  - scope:
      path: ""
      type: "manual-writing-cases"
    values:
      layout: "tutorial"
      headerImage: "/assets/images/tutorial/markdown-header-image-20mpx.jpg"
  - scope:
      path: ""
      type: "electric-machinery-principles"
    values:
      layout: "tutorial-2l"
      headerImage: "/assets/images/tutorial/markdown-header-image-20mpx.jpg"
  - scope:
      path: "*/index.html"
    values:
      layout: "page-container"

disable_disk_cache: BOOL

plugins:
  - jekyll-seo-tag